import { type NextRequest, NextResponse } from 'next/server';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { getPrayerTimes } from '../../../prayerTimes';

const PRAYER_KEYS = ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'] as const;

function cleanTime(raw: string): string {
  return raw ? raw.replace(/\s*\(.*\)/, '') : '';
}

/** Strip non-WinAnsi characters that pdf-lib StandardFonts can't encode */
function safeText(text: string): string {
  return text.replace(/[^\x20-\x7E\xA0-\xFF]/g, '');
}

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const months = Math.min(Math.max(parseInt(searchParams.get('months') || '12', 10), 1), 12);

  const queryParams: any = {};
  for (const [key, value] of searchParams.entries()) {
    if (!['lang', 'months'].includes(key)) {
      queryParams[key] = value;
    }
  }

  if (!queryParams.address && !(queryParams.latitude && queryParams.longitude)) {
    return new NextResponse('Provide address or latitude+longitude', { status: 400 });
  }

  try {
    const result = await getPrayerTimes(queryParams, months);
    if (!result?.data?.length) {
      return new NextResponse('No prayer times data', { status: 500 });
    }

    const locationLabel = queryParams.address || `${queryParams.latitude}, ${queryParams.longitude}`;

    // Group by month
    const monthGroups: Map<string, any[]> = new Map();
    for (const day of result.data) {
      const key = `${day.date.gregorian.month.number}-${day.date.gregorian.year}`;
      if (!monthGroups.has(key)) monthGroups.set(key, []);
      monthGroups.get(key)!.push(day);
    }

    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const pageW = 841.89; // A4 landscape
    const pageH = 595.28;
    const margin = 40;
    const tableW = pageW - margin * 2;

    const colWidths = [30, 50, ...PRAYER_KEYS.map(() => (tableW - 80) / PRAYER_KEYS.length)];
    const headers = ['Day', 'Date', ...PRAYER_KEYS.map(String)];
    const rowH = 16;

    for (const [, days] of monthGroups) {
      const page = pdfDoc.addPage([pageW, pageH]);
      const firstDay = days[0];
      const title = `${firstDay.date.gregorian.month.en} ${firstDay.date.gregorian.year}`;
      const hijri = safeText(`${firstDay.date.hijri.month.en} ${firstDay.date.hijri.year} AH`);

      // Title
      page.drawText(title, { x: margin, y: pageH - margin, size: 16, font: fontBold, color: rgb(0.1, 0.1, 0.1) });
      page.drawText(`${hijri}  |  ${locationLabel}`, {
        x: margin,
        y: pageH - margin - 18,
        size: 9,
        font,
        color: rgb(0.4, 0.4, 0.4),
      });

      let y = pageH - margin - 45;

      // Header row bg
      page.drawRectangle({ x: margin, y: y - 2, width: tableW, height: rowH + 2, color: rgb(0.93, 0.95, 0.98) });

      // Header text
      let x = margin;
      for (let i = 0; i < headers.length; i++) {
        page.drawText(headers[i], { x: x + 3, y: y + 3, size: 8, font: fontBold, color: rgb(0.2, 0.2, 0.2) });
        x += colWidths[i];
      }
      y -= rowH + 4;

      // Header line
      page.drawLine({
        start: { x: margin, y },
        end: { x: margin + tableW, y },
        thickness: 0.5,
        color: rgb(0.3, 0.3, 0.3),
      });
      y -= 4;

      // Data rows
      for (const day of days) {
        if (y < margin + 30) break;

        const isFriday = day.date.gregorian.weekday.en === 'Friday';
        if (isFriday) {
          page.drawRectangle({ x: margin, y: y - 2, width: tableW, height: rowH, color: rgb(0.94, 0.97, 1) });
        }

        x = margin;
        page.drawText(day.date.gregorian.day, { x: x + 3, y: y + 3, size: 7, font, color: rgb(0.1, 0.1, 0.1) });
        x += colWidths[0];
        page.drawText(day.date.gregorian.weekday.en.substring(0, 3), {
          x: x + 3,
          y: y + 3,
          size: 7,
          font,
          color: rgb(0.3, 0.3, 0.3),
        });
        x += colWidths[1];

        for (let i = 0; i < PRAYER_KEYS.length; i++) {
          const time = cleanTime(day.timings[PRAYER_KEYS[i]]);
          page.drawText(time, { x: x + 3, y: y + 3, size: 7, font, color: rgb(0.1, 0.1, 0.1) });
          x += colWidths[i + 2];
        }

        y -= rowH;
        // Row line
        page.drawLine({
          start: { x: margin, y: y + rowH - 2 },
          end: { x: margin + tableW, y: y + rowH - 2 },
          thickness: 0.15,
          color: rgb(0.85, 0.85, 0.85),
        });
      }

      // Footer
      page.drawText('Generated by pray.ahmedelywa.com', {
        x: margin,
        y: margin - 10,
        size: 7,
        font,
        color: rgb(0.6, 0.6, 0.6),
      });
    }

    const pdfBytes = await pdfDoc.save();

    const filename = `prayer-times-${locationLabel.replace(/[^a-zA-Z0-9]/g, '-')}.pdf`;

    return new NextResponse(Buffer.from(pdfBytes), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'public, max-age=86400',
      },
    });
  } catch (err: any) {
    return new NextResponse(err.message || 'Internal error', { status: 500 });
  }
}
