export default [
  { value: 0, label: 'Shia Ithna-Ansari' },
  { value: 1, label: 'University of Islamic Sciences, Karachi' },
  { value: 2, label: 'Islamic Society of North America' },
  { value: 3, label: 'Muslim World League' },
  { value: 4, label: 'Umm Al-Qura University, Makkah' },
  { value: 5, label: 'Egyptian General Authority of Survey' },
  { value: 7, label: 'Institute of Geophysics, University of Tehran' },
  { value: 8, label: 'Gulf Region' },
  { value: 9, label: 'Kuwait' },
  { value: 10, label: 'Qatar' },
  { value: 11, label: 'Majlis Ugama Islam Singapura, Singapore' },
  { value: 12, label: 'Union Organization islamic de France' },
  { value: 13, label: 'Diyanet İşleri Başkanlığı, Turkey' },
  { value: 14, label: 'Spiritual Administration of Muslims of Russia' },
  { value: 15, label: 'Moonsighting Committee Worldwide (also requires shafaq paramteer)' },
  { value: 16, label: 'Dubai (experimental)' },
  { value: 17, label: 'Jabatan Kemajuan Islam Malaysia (JAKIM)' },
  { value: 18, label: 'Tunisia' },
  { value: 19, label: 'Algeria' },
  { value: 20, label: 'KEMENAG - Kementerian Agama Republik Indonesia' },
  { value: 21, label: 'Morocco' },
  { value: 22, label: 'Comunidade Islamica de Lisboa' },
  { value: 23, label: 'Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan' },
];
